#!/usr/bin/env bash
# Interactive Github Shell.
# Copyright (C) 2012 Henrique Moody <henriquemoody@gmail.com>.
#
# Authors
# =======
#   Henrique Moody <henriquemoody@gmail.com>
#
# Changelog
# =========
#   1.0.3   Update help message.
#   1.0.3   Update prompt with defined user data.
#   1.0.2   Created OSX compatibility
#   1.0.1   Update script structure
#   1.0.0   Base script
#

# Readonly vars
declare -r GITHUBSH_NAME=$(basename "${0}")
declare -r GITHUBSH_SOURCE="${0}"
declare -r GITHUBSH_DIRECTORY="${HOME}/.github-sh"
declare -r GITHUBSH_HISTORY="${HOME}/.github-sh_history"
declare -r GITHUBSH_BASE_DIRECTORY=$(dirname "${0}")
declare -r GITHUBSH_DESCRIPTION=$(sed -n 2p "${0}" |  sed -E 's/^# ?//g')
declare -r GITHUBSH_VERSION=$(sed -n 11p "${0}" | awk '{print $2}')
declare -r GITHUBSH_PROMPT="github"
declare -r GITHUBSH_PROMPT_CHAR="> "
declare -r GITHUBSH_HELP="Usage: ${GITHUBSH_NAME} [OPTIONS]
${GITHUBSH_DESCRIPTION}

    -h, --help      Displays this help.
    -s, --set       Defines default values for variables (\"user\", \"password\", \"project\").
    -v, --version   Displays the version of the program.
    -u, --update    Self update ${GITHUBSH_NAME}.

Report bugs on https://github.com/henriquemoody/github-sh/issues."

# Global vars
declare GITHUB_PROMPT="${GITHUBSH_PROMPT}${GITHUBSH_PROMPT_CHAR}"
declare GITHUB_USERNAME=""
declare GITHUB_PASSWORD=""
declare GITHUB_PROJECT=""

# github_internal_echo MESSAGE [COLOR [DECORATION]] 
github_internal_echo()
{
    local message="${1}"
    local color="${2}"
    local decoration="${3}"

    if [ "${color}" == "" ]
    then
       color=0
    fi

    if [ "${decoration}" == "" ]
    then
        decoration="normal"
    fi

    echo -e "\033[${color}m${message}\033[0m"

}

# github_internal_set VARIABLE [ VALUE ]
github_internal_set()
{
    local label="${1}"
    local value="${2}"

    if [ "${label}" == "password" ] && [ "${value}" == "" ]; then
        read -s -p "Type your password: " value
        echo ""
    elif [ "${value}" == "" ]; then
        read -e -p "Value for ${label}: " value
    fi

    case "${label}" in 

        username)
            GITHUB_USERNAME="${value}"
        ;;

        password)
            GITHUB_PASSWORD="${value}"
        ;;

        project)
            GITHUB_PROJECT="${value}"
        ;;

        *)
          github_internal_echo "Invalid variable \"${label}\".\n" 31
          return 2

    esac

    GITHUB_PROMPT="${GITHUBSH_PROMPT}"
    if [ ! -z "${GITHUB_PROJECT}" ]; then
        GITHUB_PROMPT="${GITHUB_PROMPT}/${GITHUB_PROJECT}"
    fi
    GITHUB_PROMPT="${GITHUB_PROMPT}${GITHUBSH_PROMPT_CHAR}"

    return 0
}

github_external_help()
{
    local MESSAGE
    local HELP_FUNCTION=github_external_help_"${1}"

    if [ ! -z "${1}" ]; then
        MESSAGE=$(
            type "${HELP_FUNCTION}" &>/dev/null \
                && ${HELP_FUNCTION} full \
                || github_internal_echo "There is no help for \"${1}\"" 31
        )
    else
        MESSAGE="GitHub Shell Help

    set     $(github_external_help_set)
    issue   Make operations with Github issues."
    fi

    github_internal_echo "${MESSAGE}\n"
}
github_external_help_set()
{
    github_internal_echo "Defines a value for an existent variable."
    if [ "${1}" == "full" ]; then
        github_internal_echo
        github_internal_echo "Usage:\n"
        github_internal_echo "  set VAR [ VALUE ]\n"
        github_internal_echo "Existent variables:\n"
        github_internal_echo "  user      : Your GitHub username."
        github_internal_echo "  password  : Your GitHub password."
        github_internal_echo "  project   : Current GitHub project."
    fi
}
github_external_help_issue()
{
    github_internal_echo "Make actions for GitHub issues."
    if [ "${1}" == "full" ]; then
        github_internal_echo "There us a full descritpion"
    fi
}
# github_external_issue ACTION NUMBER [ PROJECT [ USER ] ]
github_external_issue()
{
    if [ -z "${1}" ]
    then
        github_internal_echo "You should define a issue action. (See \"help\" for more information)" 31 1>&2
        return 2
    fi

    if [ -z "${2}" ]
    then
        github_internal_echo "You should define a issue number. (See \"help\" for more information)" 31 1>&2
        return 3
    fi

    local action="${1}"
    local number="${2}"
    local project="${3}"
    local user="${4}"
    local extra_param=""
    local url

    if [ -z "${project}" ]
    then
        if [ -z "${GITHUB_PROJECT}" ]
        then
            read -e -p "Project name: " project
        else
            project="${GITHUB_PROJECT}"
        fi
    fi

    if [ -z "${user}" ]
    then
        if [ -z "${GITHUB_USERNAME}" ]
        then
            read -e -p "User or Organization: " project
        else
            user="${GITHUB_USERNAME}"
        fi
    fi

    url="https://api.github.com/repos/${user}/${project}/issues/${number}/comments"

    if [ "${GITHUB_USERNAME}" != "" ]
    then
        extra_param="${GITHUB_USERNAME}"
        if [ "${GITHUB_PASSWORD}" != "" ]
        then
            extra_param="${extra_param}:${GITHUB_PASSWORD}"
        fi
        extra_param="-u '${extra_param}'"
    fi

    curl "${extra_param}" -L "${url}" \
        | grep body \
        | cut -d '"' -f 4- \
        | awk '{ gsub(/\\n/, "\n"); print }' \
        | while read line 
    do
        echo "${line}"
    done

}

# github_external_issue_list [ PROJECT ]
github_external_issue_list()
{
    local project="${1}"
    local url="https://api.github.com/repos"
    if [ -z "${project}" ]; then
        if [ -z "${GITHUB_PROJECT}" ]; then
            read -e -p "Project name: " project
        else
            project="${GITHUB_PROJECT}"
        fi
    fi

    url="${url}/${project}/issues"

    if [ "${GITHUB_USERNAME}" != "" ]
    then
        extra_param="${GITHUB_USERNAME}"
        if [ "${GITHUB_PASSWORD}" != "" ]
        then
            extra_param="${extra_param}:${GITHUB_PASSWORD}"
        fi
        extra_param="-u '${extra_param}'"
    fi

    echo ${url}
    JSON_CONTENT=$(curl "${extra_param}" -L "${url}" 2>/dev/null)

    echo "${JSON_CONTENT}" \
      | awk '/title/ {print NR}' \
      | while read title_line; do
          let number_line=(title_line+9)
          title=$(echo "${JSON_CONTENT}" | github_internal_jsonline ${title_line})
          number=$(echo "${JSON_CONTENT}" | github_internal_jsonline ${number_line})
          echo "${number}. ${title}"
        done
}

# github_external_set VAR [ VALUE ]
github_external_set()
{
    if [ -z "${1}" ]
    then
        github_internal_echo "username: \c" 34
        github_internal_echo "${GITHUB_USERNAME}" 32 \
            || github_internal_echo "NULL" 31

        local password=$(echo ${GITHUB_PASSWORD} | tr '[:alnum:]' '*')
        github_internal_echo "password: \c" 34
        github_internal_echo "${password}" 32 \
            || github_internal_echo "NULL" 31

        github_internal_echo "project:  \c" 34
        github_internal_echo "${GITHUB_PROJECT}" 32 \
            || github_internal_echo "NULL" 31

        return 0
    fi

    github_internal_set "${1}" "${2}" \
        && github_internal_echo "Value of \"${1}\" defined with sucess.\n" 32
}

# github_external_exit
github_external_exit()
{
    github_internal_echo "Bye!"
    exit 0
}

# Just for developers
github_external_reload()
{
    clear && ${GITHUBSH_SOURCE}
}

# github_shell
github_shell()
{
    if [ ! -f "${GITHUBSH_HISTORY}" ]; then
        history -r "${GITHUBSH_HISTORY}"
    else
        touch "${GITHUBSH_HISTORY}"
    fi

    github_internal_echo "Welcome to Github Shell - ${GITHUBSH_VERSION}" 32
    github_internal_echo "${GITHUBSH_DESCRIPTION}\n"

    history -r "${GITHUBSH_HISTORY}"

    while read -e -p "${GITHUB_PROMPT}" input; do

        if [ "${input}" == "" ]; then
            continue
        fi

        command_name=$(echo "${input}" | awk '{print $1}')
        if [ "$(echo "${input}" | wc -w | awk '{print $1}')" != 1 ]; then
            command_args=$(echo "${input}" | cut -d ' ' -f 2-)
        else
            command_args=""
        fi

		history -s "${input}"

        case "${command_name}" in

            set | issue | exit | help | reload)
                github_external_${command_name} ${command_args}
            ;;

            *)
                github_internal_echo "Command \"${command_name}\" not found." 31 1>&2
                continue
            ;;

        esac

        history -w "${GITHUBSH_HISTORY}"

    done

}


while [ "${1}" != "" ]
do

    case "${1}" in

        -h | --help)

            github_internal_echo "${GITHUBSH_HELP}"
            exit 0

        ;;

        -s | --set)

            echo "${2}"  | tr ','  '\n' | while read line
            do
                key="$(echo ${line} | cut -d '=' -f 1)"
                value="$(echo ${line} | cut -d '=' -f 2-)"
                github_external_set "${key}" "${value}"
            done

        ;;

        -V)

            github_internal_echo "${GITHUBSH_VERSION}"
            exit 0

        ;;

        -v | --version)

            github_internal_echo "${GITHUBSH_NAME} version ${GITHUBSH_VERSION}"
            github_internal_echo "${GITHUBSH_DESCRIPTION}"
            exit 0

        ;;

        -u | --update)


            TEMPORARY=/tmp/github-sh_$(date +%s)
            curl -L git.io/github-sh -o ${TEMPORARY}
            chmod +x ${TEMPORARY}
            HEAD_VERSION=$(${TEMPORARY} -V)
            if [ "${HEAD_VERSION}" ==  "${GITHUBSH_VERSION}" ]
            then
                github_internal_echo "Nothing to update." 32
                github_internal_echo "The last version of ${GITHUBSH_NAME} is ${HEAD_VERSION}."
                rm -f ${TEMPORARY}
                exit 0
            fi

            if [ ! -w "${0}" ]
            then
                github_internal_echo "You don't have permission to update ${GITHUBSH_NAME}." 31 1>&2
                rm -f ${TEMPORARY}
                exit 3
            fi

            mv ${TEMPORARY} "${0}"
            github_internal_echo "Successfully updated of ${GITHUBSH_VERSION} to ${HEAD_VERSION}" 32
            exit 0

        ;;

        *)

            if [ "${1}" != "" ]
            then
                github_internal_echo "${GITHUBSH_HELP_MESSAGE}" 1>&2
                exit 2
            fi

        ;;

    esac

    shift 2

done

github_shell
